apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yaml --volumes hostPath
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: apigateway
  name: apigateway
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.yaml --volumes hostPath
        kompose.version: 1.20.0 (f3d54d784)
      creationTimestamp: null
      labels:
        io.kompose.service: apigateway
    spec:
      containers:
      - image: gilliswerrebrouck/railway-app-api-gateway-service
        name: apigateway
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /app
          name: apigateway-hostpath0
      restartPolicy: Always
      volumes:
      - hostPath:
          path: /users/gillis/Railway-System-Architecture/users/gillis/Railway-System-Architecture/railway-app-api-gateway/target
        name: apigateway-hostpath0
status: {}
